name: bigdataafrica_docker_ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd server && docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica .
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: whoami
      - run: docker pull allisterhydra/thebigdataafrica:latest
