name: bigdataafrica_docker_ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd server && docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica .
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: whoami
      - run: docker container stop thebigdataafrica # stop the container
      - run: docker rm -v thebigdataafrica # remove the container & its volume
      - run: docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica # remove outdated image
      - run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica:latest # pull latest image
      - run: docker run --name thebigdataafrica -p ${{ secrets.PORT }}:${{ secrets.PORT }} -d ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica:latest # run updated container
      - run: docker ps -a # verify the update
